### ISSUE TITLE
"Human" is not inclusive?

### ISSUE THREAD

**Issue by MikeBishop** [NTAP/isb-ietf-config#11]
On the term "human readable," the bot suggests:

>Please consider an alternative to the term "human".
>Possibilities might include: "individual", "people", "person".

The matching regex appears to be `/\b(\w+m[ae]n(ship)?)\b/gi`.

Perhaps I'm not sufficiently inclusive, but I don't believe I've encountered the term "person readable" before.

**Comment by MikeBishop** [comment]
@LPardue beat me by 30 seconds.  :-)

**Comment by LPardue** [comment]
Consider also, lifeform

**Comment by MikeBishop** [comment]
Hm, it appears that nothing has changed since Lar's commit to address #10, which removed the `?` from this regex and prevents this from matching "human."  (Or "chairman", or "workman", so I digress.)  Yet we see a match with the regex containing a `?`.  Is it possible we're picking up an old version of the config somehow?

**Comment by LPardue** [comment]
oh, we had failed to sync to upstream. Just did that https://github.com/quicwg/.github/tree/main. Sorry Lars!

**Comment by larseggert** [comment]
Reopening this as a reminder to fix this more properly (I.e., not ignore the -ship matches).

**Comment by MikeBishop** [comment]
Perhaps a negative lookbehind?  Is "human" the only "-man" word we *don't* want to flag?

**Comment by LPardue** [comment]
Careful you don't offend Germans :D

**Comment by MikeBishop** [comment]
Consider alternative:  "Deutsch"

**Comment by rmarx** [comment]
I came here to open this exact issue, as I'm getting the same warning on "human readable" in the qlog docs :)

**Comment by larseggert** [comment]
Moved to https://github.com/ietf/terminology/issues/26, which is where the most recent config lives.
