### ISSUE TITLE
Message invalid

### ISSUE THREAD

**Issue by jpoehnelt** [NTAP/isb-ietf-config#5]
Expecting 'EOF', got 'OPEN_ENDBLOCK'

**Comment by larseggert** [comment]
I'm not sure what to make of this?

**Comment by jpoehnelt** [comment]
Sorry, looks like you fixed the message handlebars template! Let me know if you have any questions on the bot.

**Comment by larseggert** [comment]
Ah yes. YAML newbie, but I figured it out. Thanks for the bot, by the way!
